### ISSUE TITLE
Breaking change in 1.48.5

### ISSUE THREAD

**Issue by rkrump** [zrwusa/data-structure-typed#61]
Hi there,

it looks like in 1.48.5 breaking changes were introduced in a patch version.

I would highly recommend you not to do that but to bump up the major version instead.
Many JavaScript developers expect [Semantic Versioning](https://semver.org/lang/de/) to be used by libraries.

https://github.com/zrwusa/data-structure-typed/blame/61369adbddcf7d78eb2b594ed217db17ba5228f4/src/data-structures/graph/abstract-graph.ts#L75

Best Regards,
rkrump

**Comment by zrwusa** [comment]
Our previous version had a design issue, leading to minor changes using the second digit of the version number. Moderate modifications, such as certain API changes, also utilized the second digit. We anticipate addressing this somewhat unreasonable design after the release of version 2.0.0. API changes were also made to strike a balance between ES (ECMAScript) standards and Java standards. We apologize for any inconvenience caused by these adjustments and appreciate your understanding.

**Comment by rkrump** [comment]
I see, thanks for the insight :)
